-- Enable Row Level Security (RLS) on all public tables in Supabase
-- This locks down PostgREST API access while allowing direct Prisma TCP connections to function uninterrupted.

ALTER TABLE "Clinic" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Patient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Encounter" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Prescription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PrescriptionMedicine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Drug" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TreatmentGroup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TreatmentGroupItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DoctorDrugPreference" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClinicDrugPreference" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Reminder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "QueueItem" ENABLE ROW LEVEL SECURITY;
